services:
  backend:
    build: ./Backend
    env_file:
      - .env
    ports:
      - "3001:3000"
    networks:
      - harp-network

  frontend:
    build: ./Frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "8888:8888"
    depends_on:
      - backend
    networks:
      - harp-network

networks:
  harp-network:
    driver: bridge
